weights:
  technical: 0.4       # סוכנים טכניים (C1)
  fundamental: 0.2     # סוכנים פונדמנטליים (C2)
  news: 0.2            # סוכנים מבוססי אירועים / חדשות (C3)
  sentiment: 0.2       # סוכני סנטימנט (C4)
